version: '2'
services:
  bankcart-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/bankcart/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bankcart
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
